version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:3.12-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: nestjs-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - rabbitmq
      - mongodb
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/you_app'
      RABBITMQ_URI: 'amqp://guest:guest@rabbitmq:5672'
